# config/settings.yml
target_wards:
  # 東京都（既存9区）
  - 大田区
  - 葛飾区
  - 世田谷区
  - 品川区
  - 中央区
  - 墨田区
  - 江東区
  - 台東区
  - 江戸川区
  # 東京都（追加3区）
  - 足立区
  - 目黒区
  - 荒川区
  # 千葉県
  - 市川市
  - 松戸市
  - 浦安市

filters:
  price_min: 50000000
  price_max: 130000000
  price_center_min: 70000000
  price_center_max: 90000000
  area_min: 50
  floor_plan_min: "2LDK"
  minutes_to_station_max: 15

market:
  min_sample_count: 20
  years_range: 2
  age_brackets: ["0-10", "11-20", "21-30", "31+"]
  area_brackets: ["50-60", "61-70", "71-80", "81+"]

schedule:
  scrape_time: "06:00"
